name: macOS CI

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.10.0
    - name: Run a qt project
      run: |
        cmake ./
        make
